#!/usr/bin/env bash
set -euo pipefail

steps="${TRACK3_TRAIN_STEPS:-3000}"
trials="${TRACK3_NUM_TRIALS:-1}"
source_script="${TRACK3_NM_SOURCE:-records/track_3_optimization/results/20260505_newton_muon/train_gpt_simple_newton_muon.py}"
generated_script="${TRACK3_GENERATED_SCRIPT:-/tmp/train_gpt_simple_newton_muon_${steps}.py}"
nproc="${NPROC_PER_NODE:-}"
if [[ -z "${nproc}" ]]; then
  if command -v nvidia-smi >/dev/null 2>&1; then
    nproc="$(nvidia-smi -L | wc -l)"
  else
    nproc=1
  fi
fi

python3 - "${source_script}" "${generated_script}" "${steps}" <<'PY'
import sys
from pathlib import Path

src = Path(sys.argv[1])
dst = Path(sys.argv[2])
steps = sys.argv[3]
text = src.read_text()
text = text.replace(
    "    train_steps = 3300",
    f"    train_steps = {steps}  # generated by tools/run_track3_newton_muon.sh",
)
text = text.replace(
    'print0(f"Running PyTorch {torch.version.__version__} compiled for CUDA {torch.version.cuda}"',
    'print0("Track3 Newton-Muon generated run: train_steps=' + steps + '")\n'
    'print0(f"Running PyTorch {torch.version.__version__} compiled for CUDA {torch.version.cuda}"',
)
dst.write_text(text)
PY

python3 -m py_compile "${generated_script}"

if [[ "${TRACK3_DRY_RUN:-0}" == "1" ]]; then
  echo "generated ${generated_script}"
  exit 0
fi

torchrun --standalone --nproc_per_node="${nproc}" "${generated_script}" "${trials}"
